import type { RawScanReport } from './scan-schema';

const ipv4Pattern = /\b(?:\d{1,3}\.){3}\d{1,3}\b/g;
const macPattern = /\b[0-9a-fA-F]{2}(?::[0-9a-fA-F]{2}){5}\b/g;
const hostnameKeys = new Set(['hostname', 'host', 'name']);

function maskString(value: string) {
  return value
    .replace(macPattern, 'xx:xx:xx:xx:xx:xx')
    .replace(ipv4Pattern, (ip) => {
      const parts = ip.split('.');
      if (parts.length !== 4) return ip;
      return `${parts[0]}.${parts[1]}.x.x`;
    });
}

function redact(value: unknown, key = ''): unknown {
  if (Array.isArray(value)) return value.map((item) => redact(item, key));
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([childKey, childValue]) => [
      childKey,
      redact(childValue, childKey),
    ]));
  }
  if (typeof value !== 'string') return value;
  if (hostnameKeys.has(key.toLowerCase()) && !/^(http|https|domain|gateway|agent|host|router)$/i.test(value)) {
    return '[redacted-hostname]';
  }
  return maskString(value);
}

export function buildSafeShareReport(raw: RawScanReport) {
  const redacted = redact(raw) as RawScanReport;
  return {
    ...redacted,
    safe_to_share: {
      enabled: true,
      mode: 'frontend_safe_share',
      applied: {
        mask_public_ip: true,
        mask_private_ip: true,
        mask_mac: true,
        mask_hostnames: true,
      },
      notes: [
        'Generated by the Wails frontend from an imported iad-agent JSON report.',
        'Review before sharing externally; free-form banners and probe errors may still contain environment-specific text.',
      ],
    },
  };
}

export function safeShareFilename(scanId: string) {
  return `${scanId || 'iad-scan'}-safe-share.json`;
}
