// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ippool} from '../models';

export function AddDiscoveryPoolEvidence(arg1:string,arg2:ippool.EvidenceItem):Promise<boolean>;

export function AddDiscoveryPoolSeed(arg1:string):Promise<void>;

export function CancelScan():Promise<void>;

export function ClearDiscoveryPoolStale():Promise<number>;

export function DiscoveryPoolDevices():Promise<Array<ippool.DevicePoolEntry>>;

export function LatestSnapshot():Promise<string>;

export function ListInterfaces():Promise<string>;

export function OpenScanFile():Promise<string>;

export function Platform():Promise<string>;

export function RunScan(arg1:string,arg2:string):Promise<string>;

export function SaveExport(arg1:string,arg2:string):Promise<string>;

export function StartDiscoveryPool(arg1:Array<string>,arg2:boolean):Promise<void>;

export function StartScan(arg1:string,arg2:string):Promise<string>;

export function StopDiscoveryPool():Promise<void>;
