// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListInterfaces() {
  return window['go']['main']['App']['ListInterfaces']();
}

export function OpenScanFile() {
  return window['go']['main']['App']['OpenScanFile']();
}

export function Platform() {
  return window['go']['main']['App']['Platform']();
}

export function RunScan(arg1, arg2) {
  return window['go']['main']['App']['RunScan'](arg1, arg2);
}

export function SaveExport(arg1, arg2) {
  return window['go']['main']['App']['SaveExport'](arg1, arg2);
}
