// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDiscoveryPoolEvidence(arg1, arg2) {
  return window['go']['main']['App']['AddDiscoveryPoolEvidence'](arg1, arg2);
}

export function AddDiscoveryPoolSeed(arg1) {
  return window['go']['main']['App']['AddDiscoveryPoolSeed'](arg1);
}

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function ClearDiscoveryPoolStale() {
  return window['go']['main']['App']['ClearDiscoveryPoolStale']();
}

export function DiscoveryPoolDevices() {
  return window['go']['main']['App']['DiscoveryPoolDevices']();
}

export function LatestSnapshot() {
  return window['go']['main']['App']['LatestSnapshot']();
}

export function ListInterfaces() {
  return window['go']['main']['App']['ListInterfaces']();
}

export function OpenScanFile() {
  return window['go']['main']['App']['OpenScanFile']();
}

export function Platform() {
  return window['go']['main']['App']['Platform']();
}

export function RunScan(arg1, arg2) {
  return window['go']['main']['App']['RunScan'](arg1, arg2);
}

export function SaveExport(arg1, arg2) {
  return window['go']['main']['App']['SaveExport'](arg1, arg2);
}

export function StartDiscoveryPool(arg1, arg2) {
  return window['go']['main']['App']['StartDiscoveryPool'](arg1, arg2);
}

export function StartScan(arg1, arg2) {
  return window['go']['main']['App']['StartScan'](arg1, arg2);
}

export function StopDiscoveryPool() {
  return window['go']['main']['App']['StopDiscoveryPool']();
}
