// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListInterfaces():Promise<string>;

export function OpenScanFile():Promise<string>;

export function Platform():Promise<string>;

export function RunScan(arg1:string,arg2:string):Promise<string>;

export function SaveExport(arg1:string,arg2:string):Promise<string>;
